reviewers:
  defaults:
    - repository-owners # group

  groups:
    repository-owners:
      - manhuakatalon
      - hmman3141

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
  number_of_reviewers: 3
  last_files_match_only: false
