name: Mirror to BitBucket Github Action

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # <-- clone with complete history

      - name: Push
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
          username: huaminhman15112000@gmail.com
          spacename: huaminhman15112000@gmail.com
          repository: Katalon-test-management-testops
          password: ${{ secrets.BITBUCKET_PASSWORD }}
