name: Auto Request Review

on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml # Config file location override
        
#       - name: Request review based on files changes and/or groups the author belongs to
#         uses: kentaro-m/auto-assign-action@v1.2.5
#         with:
#           configuration-path: '.github/reviewers-kentaro.yml' # Only needed if you use something other than .github/auto_assign.yml
